**Limpieza datasets**

**1. Behavior**

- **customer_id**: cambiar a minúscula toda la columna
- **behavior_churn_signal**: es una columna booleana. Crear una nueva columna tipo boolean.
- **cart_abandon_rate**, **return_rate**: convertir en % porque en el dataset "products" está así.

**2. Customers**

- **customer_id**: cambiar a minúscula toda la columna
- **gender**: cambiar a minúscula toda la columna
- **country**: cambiar a minúscula toda la columna
- **registration_date**: cambiar a dtype fecha
- **churn_label**: es una columna booleana. Crear una nueva columna tipo boolean.

**3. Products**

- **product_id**: cambiar a minúscula toda la columna
- **category**: cambiar a minúscula toda la columna y sustituir espacios por "_"

**4. Transactions**

- **transaction_id**, **customer_id**, **product_id**: cambiar a minúscula toda la columna
- **order_date**: cambiar a dtype fecha
- **payment_method**: cambiar a minúscula toda la columna y sustituir espacios por "_"
- **device_type**: cambiar a minúscula toda la columna
- **discount_applied**: convertir en % porque en el dataset "products" está así.
- **fraud_label**: es una columna booleana. Crear una nueva columna tipo boolean.

Una vez tenemos los cambios claros, procedemos a realizarlos paso a paso.

1. Importamos librería y funciones generales

In [3]:
# Tratamiento de datos

import pandas as pd
pd.set_option('display.max_columns', None)
import sys
import os

# Añadimos ruta al proyecto para poder importar módulos
project_root = os.path.abspath(os.path.join(".."))
sys.path.append(project_root)

# ----------

# Funciones personalizadas

from src.utils.cleaning_utils import (
    limpiar_behavior,
    limpiar_customers,
    limpiar_products,
    limpiar_transactions
)

2. Cargamos los datasets desde la ruta data/01_raw

In [4]:

ruta_raw = "../data/01_raw/"

behavior = pd.read_csv(ruta_raw + "behavior.csv")
customers = pd.read_csv(ruta_raw + "customers.csv")
products = pd.read_csv(ruta_raw + "products.csv")
transactions = pd.read_csv(ruta_raw + "transactions.csv")

print("Datasets cargados correctamente.")

Datasets cargados correctamente.

3. Vemos los datasets originales antes de hacer los cambios que hemos planteado anteriormente.

In [5]:
print("=== BEFORE CLEANING: Behavior ===")
display(behavior.head())

print("=== BEFORE CLEANING: Customers ===")
display(customers.head())

print("=== BEFORE CLEANING: Products ===")
display(products.head())

print("=== BEFORE CLEANING: Transactions ===")
display(transactions.head())

=== BEFORE CLEANING: Behavior ===

,customer_id,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
0,CUST000001,8.12,21,0.95,0.37,1,3.39,1
1,CUST000002,3.96,9,0.16,0.03,3,4.46,1
2,CUST000003,12.42,24,0.71,0.01,1,4.88,0
3,CUST000004,16.82,18,0.21,0.09,1,1.73,0
4,CUST000005,6.78,2,0.52,0.22,0,2.16,1

=== BEFORE CLEANING: Customers ===

,customer_id,age,gender,country,registration_date,loyalty_score,lifetime_value,churn_label
0,CUST000001,25,Male,Canada,2021-08-02,37.45,19019.21,1
1,CUST000002,65,Male,UK,2018-10-13,73.20,12013.30,0
2,CUST000003,19,Male,India,2018-03-07,15.60,3204.29,1
3,CUST000004,19,Other,India,2021-05-17,5.81,17336.91,0
4,CUST000005,52,Female,India,2021-12-07,60.11,14190.64,0

=== BEFORE CLEANING: Products ===

  product_id     category   price  margin_percentage  popularity_score
0  PROD00001      Fashion  377.67              38.28             73.20
1  PROD00002  Electronics  600.67              10.46             15.60
2  PROD00003       Beauty   62.79              35.32             60.11
3  PROD00004       Sports  709.53               5.72             96.99
4  PROD00005       Sports  833.28              12.43             18.18

=== BEFORE CLEANING: Transactions ===

,transaction_id,customer_id,product_id,order_date,order_value,payment_method,device_type,discount_applied,shipping_delay_days,fraud_label
0,TXN0000001,CUST020953,PROD00229,2019-02-21,753.08,Debit Card,Mobile,0.19,4,0
1,TXN0000002,CUST003359,PROD01386,2023-02-25,9.27,Credit Card,Tablet,0.48,8,0
2,TXN0000003,CUST000977,PROD00192,2020-03-23,393.11,Crypto,Tablet,0.37,3,1
3,TXN0000004,CUST006516,PROD01467,2022-08-23,121.83,UPI,Mobile,0.30,8,0
4,TXN0000005,CUST009116,PROD01658,2023-11-16,826.59,Debit Card,Tablet,0.08,0,0

4. Aplicamos las funciones de limpieza y mostramos los cambios

Behavior

In [9]:
print("=== Cleaning Behavior ===")

behavior_clean = limpiar_behavior(behavior)

print("Nuevas columnas creadas:")
[k for k in behavior_clean.columns if "binaria" in k or "yes_no" in k]

display(behavior_clean.head())

=== Cleaning Behavior ===
→ Creando copia del dataframe: behavior
Nuevas columnas creadas:

,customer_id,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal,behavior_churn_signal_binaria,behavior_churn_signal_yes_no
0,cust000001,8.12,21,95.0,37.0,1,3.39,1,True,Yes
1,cust000002,3.96,9,16.0,3.0,3,4.46,1,True,Yes
2,cust000003,12.42,24,71.0,1.0,1,4.88,0,False,No
3,cust000004,16.82,18,21.0,9.0,1,1.73,0,False,No
4,cust000005,6.78,2,52.0,22.0,0,2.16,1,True,Yes

Customers

In [8]:
print("=== Cleaning Customers ===")

customers_clean = limpiar_customers(customers)

print("Nuevas columnas creadas:")
[k for k in customers_clean.columns if "binaria" in k or "yes_no" in k]

display(customers_clean.head())

=== Cleaning Customers ===
→ Creando copia del dataframe: customers
Nuevas columnas creadas:

,customer_id,age,gender,country,registration_date,loyalty_score,lifetime_value,churn_label,churn_label_binaria,churn_label_yes_no
0,cust000001,25,male,canada,2021-08-02,37.45,19019.21,1,True,Yes
1,cust000002,65,male,uk,2018-10-13,73.20,12013.30,0,False,No
2,cust000003,19,male,india,2018-03-07,15.60,3204.29,1,True,Yes
3,cust000004,19,other,india,2021-05-17,5.81,17336.91,0,False,No
4,cust000005,52,female,india,2021-12-07,60.11,14190.64,0,False,No

Products

In [10]:
print("=== Cleaning Products ===")

products_clean = limpiar_products(products)

display(products_clean.head())

=== Cleaning Products ===
→ Creando copia del dataframe: products

  product_id     category   price  margin_percentage  popularity_score
0  prod00001      fashion  377.67              38.28             73.20
1  prod00002  electronics  600.67              10.46             15.60
2  prod00003       beauty   62.79              35.32             60.11
3  prod00004       sports  709.53               5.72             96.99
4  prod00005       sports  833.28              12.43             18.18

Transactions

In [11]:
print("=== Cleaning Transactions ===")

transactions_clean = limpiar_transactions(transactions)

print("Nuevas columnas creadas:")
[k for k in transactions_clean.columns if "binaria" in k or "yes_no" in k]

display(transactions_clean.head())

=== Cleaning Transactions ===
→ Creando copia del dataframe: transactions
Nuevas columnas creadas:

,transaction_id,customer_id,product_id,order_date,order_value,payment_method,device_type,discount_applied,shipping_delay_days,fraud_label,fraud_label_binaria,fraud_label_yes_no
0,txn0000001,cust020953,prod00229,2019-02-21,753.08,debit_card,mobile,19.0,4,0,False,No
1,txn0000002,cust003359,prod01386,2023-02-25,9.27,credit_card,tablet,48.0,8,0,False,No
2,txn0000003,cust000977,prod00192,2020-03-23,393.11,crypto,tablet,37.0,3,1,True,Yes
3,txn0000004,cust006516,prod01467,2022-08-23,121.83,upi,mobile,30.0,8,0,False,No
4,txn0000005,cust009116,prod01658,2023-11-16,826.59,debit_card,tablet,8.0,0,0,False,No

Una vez hechos los cambios, procedemos a guardar los nuevos datasets en la carpeta data/02_processed

In [12]:
ruta_processed = "../data/02_processed/"

behavior_clean.to_csv(ruta_processed + "behavior_clean.csv", index=False)
customers_clean.to_csv(ruta_processed + "customers_clean.csv", index=False)
products_clean.to_csv(ruta_processed + "products_clean.csv", index=False)
transactions_clean.to_csv(ruta_processed + "transactions_clean.csv", index=False)

print("Archivos guardados en data/02_processed/")

Archivos guardados en data/02_processed/